### **Intro Linguagem R**

In [ ]:
# x é igual a 20
X = 20
X


[1] 20

In [ ]:
# x é 10
X <- 10
X

[1] 10

In [ ]:
# usando o combine:
X <- c (1:10)
X

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
help(c)

Warning message in seq_len(head.end.idx):
“first element used of 'length.out' argument”
ERROR while rich displaying an object: Error in seq_len(head.end.idx): argument must be coercible to non-negative integer

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_conte

c                     package:base                     R Documentation

_C_o_m_b_i_n_e _V_a_l_u_e_s _i_n_t_o _a _V_e_c_t_o_r _o_r _L_i_s_t

_D_e_s_c_r_i_p_t_i_o_n:

     This is a generic function which combines its arguments.

     The default method combines its arguments to form a vector.  All
     arguments are coerced to a common type which is the type of the
     returned value, and all attributes except names are removed.

_U_s_a_g_e:

     ## S3 Generic function
     c(...)
     
     ## Default S3 method:
     c(..., recursive = FALSE, use.names = TRUE)
     
_A_r_g_u_m_e_n_t_s:

     ...: objects to be concatenated.  All ‘NULL’ entries are dropped
          before method dispatch unless at the very beginning of the
          argument list.

recursive: logical.  If ‘recursive = TRUE’, the function recursively
          descends through lists (and pairlists) combining all their
          elements into a vector.

use.names: logical indicating if ‘names’ should be preserved.

_D_e_t_a_i_l_s:

     The output type is determined from the highest type of the
     components in the hierarchy NULL < raw < logical < integer <
     double < complex < character < list < expression.  Pairlists are
     treated as lists, whereas non-vector components (such as ‘name’s /
     ‘symbol’s and ‘call’s) are treated as one-element ‘list’s which
     cannot be unlisted even if ‘recursive = TRUE’.

     Note that in R < 4.1.0, ‘factor’s were treated only via their
     internal ‘integer’ codes: now there is ‘c.factor’ method which
     combines factors into a factor.

     ‘c’ is sometimes used for its side effect of removing attributes
     except names, for example to turn an ‘array’ into a vector.
     ‘as.vector’ is a more intuitive way to do this, but also drops
     names.  Note that methods other than the default are not required
     to do this (and they will almost certainly preserve a class
     attribute).

     This is a primitive function.

_V_a_l_u_e:

     ‘NULL’ or an expression or a vector of an appropriate mode.  (With
     no arguments the value is ‘NULL’.)

_S_4 _m_e_t_h_o_d_s:

     This function is S4 generic, but with argument list ‘(x, ...)’.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘unlist’ and ‘as.vector’ to produce attribute-free vectors.

_E_x_a_m_p_l_e_s:

     c(1,7:9)
     c(1:5, 10.5, "next")
     
     ## uses with a single argument to drop attributes
     x <- 1:4
     names(x) <- letters[1:4]
     x
     c(x)          # has names
     as.vector(x)  # no names
     dim(x) <- c(2,2)
     x
     c(x)
     as.vector(x)
     
     ## append to a list:
     ll <- list(A = 1, c = "C")
     ## do *not* use
     c(ll, d = 1:3) # which is == c(ll, as.list(c(d = 1:3)))
     ## but rather
     c(ll, d = list(1:3))  # c() combining two lists
     
     c(list(A = c(B = 1)), recursive = TRUE)
     
     c(options(), recursive = TRUE)
     c(list(A = c(B = 1, C = 2), B = c(E = 7)), recursive = TRUE)
     

In [ ]:
# retornando valores maiores que 8
X [(X > 8)]

[1]  9 10

In [ ]:
# valores maiores e iguais a 8
X [(X >= 8)]

[1]  8  9 10

In [ ]:
# Pergunta 1) Pensando desta forma, quais seriam as condições para garantir que o vetor retorne 
# apenas os valores 1, 2, 3, 4 e 5?

X[(X < 6)]



[1] 1 2 3 4 5

In [ ]:
# usando o operador lógico OU |

X [(X > 8) | (X < 5)]

[1]  1  2  3  4  9 10

In [ ]:
# operador lógico E &. Tem que satisfazer as duas condições:

X [(X < 8) & (X > 5)]

[1] 6 7

In [ ]:
# Pergunta 2) O que acontece se você escrever as condicionais do vetor desta forma
#  X [(X > 8) & (X < 5)]? E por que isso aconteceu? 

X [(X > 8) & (X < 5)]

# Não há retorno, pois não há numeros que satisfaçam as duas condições.

integer(0)

In [ ]:
# interagindo com valores de vetor. Ao invés de retornar um número, ele retorna true ou false.
X > 8

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE

In [ ]:
X < 5

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE

In [ ]:
X > 8 | X < 5

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE

In [ ]:
# retornando os valores do vetor acima:

X [c (T, T, T, T, F, F, F, F, T, T)]

[1]  1  2  3  4  9 10

In [ ]:
# Pergunta 3) Revise um dos primeiros blocos de código que utilizamos aqui no e-book: 
# X [(X > 8)]. Você consegue dizer o que o elemento (X > 8) faz? Explique o comportamento
# deste elemento para o resultado que chegou.

# Apresenta os valores em X maiores que 8. Ele verifica cada elemento do vetor
# e aqueles que atendem à condição serão apresentados em seguida.

In [ ]:
X

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
# adicionando strings ao vetor
X <- c('a','b','c','d','e','f','g','h','i','j')
X

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j"

In [ ]:
# filtrando elementos maiores ou iguais que d
X [(X >= 'd')]

[1] "d" "e" "f" "g" "h" "i" "j"

In [ ]:
# funciona com elementos intercalados
X <- c('f','c','b','d','g','h','a','i','e','j')
X [(X >= 'd')]

[1] "f" "d" "g" "h" "i" "e" "j"

In [ ]:
# identificando o tipo de dado
X <- 1
str(X)


 num 1


In [ ]:
# verificando se o valor é numerico:

X <- 1
is.numeric(X)
X

[1] TRUE

[1] 1

In [ ]:
# verificando se é número inteiro:

X <- 3
is.integer(X)
X

# é false pois está como tipo numeric

[1] FALSE

[1] 3

In [ ]:
# convertendo para inteiro:

X <- as.integer(3)
is.integer(X)
X

[1] TRUE

[1] 3

In [ ]:
# lembrando que o is.integer é false pois não foi atribuido o tipo integer
X <- 2+2
is.integer(X)
is.numeric(X)
X

[1] FALSE

[1] TRUE

[1] 4

In [ ]:
# verificando se é character:
X <- '2'
is.character(X)
X

# Character sempre entre aspas

[1] TRUE

[1] "2"

In [ ]:
# verificando se é lógico:
X <- TRUE
is.logical(X)
X

[1] TRUE

[1] TRUE

In [ ]:
# verificando vetores:

X <- c(5,6,7,8)
is.vector(X)
X

[1] TRUE

[1] 5 6 7 8

In [ ]:
X <- c(9:12)
is.vector(X)

[1] TRUE

### **Matrizes**

In [ ]:
# matriz 2,3 = 2 linhas e 3 colunas. com true percorre a linha:

valores <- c(1,2,3,4,5,6)
X <- matrix(valores, nrow = 2, ncol = 3, byrow = TRUE)
X

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
# com o False, percorre a coluna:

X <- matrix(valores, nrow = 2, ncol = 3, byrow = FALSE)
X

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [42]:
# matriz 3,3

X <- matrix(valores, nrow = 3, ncol = 3, byrow = FALSE)
X

[,1] [,2] [,3]
[1,] 1    4    1   
[2,] 2    5    2   
[3,] 3    6    3

In [43]:
# matriz 3,2 omitindo o byrow entra valor padrão

X <- matrix(valores, nrow = 3, ncol = 2)
X

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

### **Funções**

In [44]:
# define o x como função de a*b
X <- function(a,b){
 a * b
}

X(5,2)

[1] 10

In [45]:
X <- function(a,b){ 

  a * b 

} 

is.integer(X(5,2))

[1] FALSE